<Document>
<Version> 22 </Version>
<JMadonnaVersion> 9.0.125 </JMadonnaVersion>
<Bounds> 0 0 1280 704 </Bounds>
<NotesEditor>
<jeditorpane>
<size>13</size><family>Lucida Grande</family>



</jeditorpane>
</NotesEditor>
<jmadonna.EquationPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>12</size><family>Serif</family>


METHOD RK4

STARTTIME = 0
STOPTIME=1000
DT = 0.0004

d/dt(S) = - beta*I*S + delta1CTL
d/dt(I) = beta*I*S - v*I
d/dt(R) = v*I

; INITIAL STATE IN PRIMO INFECTION


;S_0 = 1e7
S_0 = 1e7
Init S = S_0
Init I = 1000
Init R = 0
beta = 1e-8
v = 0.020 

time_CTL = 4
deltap = 1
deltapp = 1
delta1CTL = if time <lt> time_CTL then 0 else deltap * ( deltapp * (time - time_CTL) ) 


Slog_perml = log10(S)




</jeditorpane>
</jmadonna.EquationPanel>

<imethod> stiff </imethod>
<Sliders>
<SliderInfo>
<name> v </name>
<default> 0.0 </default>
<min> 0.0 </min>
<max> 0.04 </max>
<inc> 0.0010 </inc>
<log> false </log>
<neg> false </neg>

</SliderInfo>
</Sliders>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 1.0 </DividerPercent>
<Orientation> -1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 0 </SelectedIndex>
<graph.COutputFrame>
<DocPanel>
<Name>
Graph 1
</Name>
</DocPanel>
<slidersVisible> true </slidersVisible>

<SingleView>
<graph.COutputView>
<Name> Graph </Name>
<GraphToolBar>
</GraphToolBar>
<Plot>
<LineWidth> 1 </LineWidth>
</Plot>
<OV_XVAR>
<VI_SYMBOL> TIME </VI_SYMBOL>
</OV_XVAR>
<OV_YVARS>
<OV_YVAR_I>
<VI_SYMBOL> S </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> I </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> true </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> R </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
</OV_YVARS>
<OV_TABLE> false </OV_TABLE>
<OV_FFT> false </OV_FFT>
<OV_COLORS> true </OV_COLORS>
<OV_STYLES> false </OV_STYLES>
<OV_OSCMODE> false </OV_OSCMODE>
<OV_LINES> true </OV_LINES>
<OV_POINTS> true </OV_POINTS>
<OV_GRID> false </OV_GRID>
<OV_DBTN> true </OV_DBTN>
<OV_LEGEND> false </OV_LEGEND>
<OV_PARAMS> false </OV_PARAMS>
<OV_READOUT> false </OV_READOUT>
<OV_INITCOND> false </OV_INITCOND>
<OV_RDOUTFXFY> 0.0 0.0 </OV_RDOUTFXFY>
<OV_ZSNORMAL>
</OV_ZSNORMAL>
<OV_ZSFFT>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> false </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSFFT>
<OV_ZSOSCMODE>
</OV_ZSOSCMODE>
<OV_AUTOLABEL> 0 0 </OV_AUTOLABEL>
<OV_AUTOLABEL> 1 0 </OV_AUTOLABEL>
<OV_AUTOLABEL> 2 0 </OV_AUTOLABEL>
<OV_X1LABELS>        TIME    </OV_X1LABELS>
<OV_Y1LABELS>        S, R    </OV_Y1LABELS>
<OV_Y2LABELS>        I    </OV_Y2LABELS>
<OV_LEGENDXY> 0.30000001192092896 0.5 </OV_LEGENDXY>
<OV_PARAMSXY> 0.30000001192092896 0.5 </OV_PARAMSXY>
</graph.COutputView>
</SingleView>
</graph.COutputFrame>
</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

<ChemicalReactionDialog>
<ShowRates> true </ShowRates>
<ShowConsts> true </ShowConsts>
<ShowInits> true </ShowInits>
<ShowDiffs> true </ShowDiffs>
</ChemicalReactionDialog>
</Document>
